[build]
  publish = "public/"
  command = "yarn build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "12.13.0"

[[redirects]]
  from = "/"
  to = "https://www.greenwoodjs.dev"
  status = 301
  force = true