name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node: [20, 22]

    steps:
      - uses: actions/checkout@v4
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-chromium-${{ hashFiles('.github/workflows/chromium-lib-install.sh') }}
          restore-keys: |
            ${{ runner.os }}-apt-chromium-
      - name: Install Chromium Library Dependencies
        run: |
          sh ./.github/workflows/chromium-lib-install.sh
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "yarn"
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest
      - name: Installing project dependencies
        run: |
          yarn install --frozen-lockfile && yarn lerna bootstrap
      - name: Lint
        run: |
          yarn lint
      - name: Check Formatting
        run: |
          yarn run format:check
      - name: Test
        run: |
          yarn test
      - name: Build
        run: |
          yarn clean && yarn build
